alphagov/govuk-dependencies

Gemfile, Procfile
Heroku didn't deploy correctly so we have updated the Gemfile to specify
the Ruby version and the Procfile to allow the correct port
=> Updated Gemfile & Procfile for Heroku

Gemfile, Gemfile.lock, spec/app_spec.rb, spec/spec_helper.rb
Add some test dependencies, configure RSpec and add a feature spec.
https://trello.com/c/HtR7PDed/58-get-prs-by-dependabot
=> Set up testing dependencies and basic feature spec

Gemfile, Gemfile.lock, lib/gateways/pull_request.rb, lib/loader.rb, spec/gateways/pull_request_spec.rb, spec/use_cases/fetch_pull_requests_spec.rb
https://trello.com/c/HtR7PDed/58-get-prs-by-dependabot
This is the implementation of the PullRequest gateway - this uses Octokit to fetch open PRs by dependabot from github and translates the response into domain objects
=> Create PullRequest Gateway

lib/gateways/pull_request.rb, spec/gateways/pull_request_spec.rb
Increase rate limits by using a token
https://trello.com/c/95E9iPMb/55-get-github-oauth-token-for-use-with-the-api
=> Use the Github Token

Gemfile, Gemfile.lock, app.rb, lib/domain/pull_request.rb, lib/gateways/pull_request.rb, lib/loader.rb, lib/presenters/pull_requests_by_application.rb, lib/use_cases/fetch_pull_requests.rb, public/assets/application.css, spec/gateways/pull_request_spec.rb, spec/presenters/pull_requests_by_application_spec.rb, spec/spec_helper.rb, views/index.erb
Initial markup for displaying pull requests grouped by application to be improved upon in subsequent PRs.
https://trello.com/c/8e8vmHtG/71-per-application-view
https://trello.com/c/l5EP4QUD/63-filter-dependabot-prs-by-application
=> Create View for Pull Requests By Application

lib/gateways/pull_request.rb, lib/presenters/pull_requests_by_application.rb, spec/app_spec.rb, spec/presenters/pull_requests_by_application_spec.rb, views/index.erb
Add links to the application title
Add count of open pull requests per application
Make github access token optional
https://trello.com/c/8e8vmHtG/71-per-application-view
=> App view improvements

lib/domain/team.rb, lib/gateways/team.rb, lib/loader.rb, spec/fixtures/multiple_teams_with_multiple_applications.json, spec/fixtures/team_with_one_application.json, spec/fixtures/team_with_two_applications.json, spec/gateways/team_spec.rb
Gateway to pull team data from https://docs.publishing.service.gov.uk/apps.json
Build Team domain objects 
https://trello.com/c/TNAQDgCU/64-filter-dependabot-prs-by-team
=> Add Team Gateway

public/assets/application.css, spec/app_spec.rb, views/gem.erb, views/index.erb, views/team.erb
https://trello.com/c/HtN4YH50/80-display-message-when-there-are-no-pull-requests-found
Depends on #12
=> Add error message for if no pull requests are found

spec/app_spec.rb, views/gem.erb, views/index.erb, views/team.erb
A little 🎂 if all the PRs have been merged.
https://trello.com/c/HtN4YH50
=> Celebrate if there aren't any PRs open

app.rb, spec/app_spec.rb, views/gem.erb, views/index.erb, views/team.erb
Displays the dependabot PRs for each application per-team
https://trello.com/c/FSQd5ZN7/83-individual-team-view
=> Add page for team specific pull requests

Rakefile, bin/dependaseal, dependaseal.rb, lib/gateways/slack_message.rb, lib/use_cases/send_slack_messages.rb, spec/dependaseal_spec.rb, spec/gateways/slack_message_spec.rb, spec/use_cases/send_slack_messages_spec.rb
Additionally fixes the edge case of PRs with no team assigned
https://trello.com/c/hf06yc6n/61-push-messages-into-slack-once-per-day
=> Add executable to send slack messages

app.rb, views/gem.erb, views/index.erb, views/layout.erb, views/team.erb
Use a layout to remove duplication from the view files.
https://trello.com/c/0hEInYKJ/79-refactor-clean-up-view-code
=> Remove duplication from views

public/assets/application.css, views/layout.erb
https://trello.com/c/aCqk8vDm/85-add-nav-bar-to-view
depends on #20
=> Add navigation bar to view

lib/use_cases/send_slack_messages.rb, public/assets/application.css, spec/dependaseal_spec.rb, spec/use_cases/send_slack_messages_spec.rb, views/layout.erb
https://trello.com/c/9ZUfHPdv/87-add-link-to-feedback
=> Add a link to the feedback board on the dashboard and slack messages

lib/gateways/pull_request.rb
Fixes: https://trello.com/c/L74FsxtM/90-fix-pull-requests-not-paginating-correctly
=> Use correct key for auto-pagination with octokit

lib/presenters/pull_requests_by_application.rb, lib/presenters/pull_requests_by_gem.rb, lib/presenters/pull_requests_by_team.rb, spec/presenters/pull_requests_by_application_spec.rb, spec/presenters/pull_requests_by_gem_spec.rb, spec/presenters/pull_requests_by_team_spec.rb
Add ordering to dashboard -
- Application view
- App name & gem name
- Gem view
- Gem name & application name
- Team view
- Team name & application PR count (high to low)
- When an application has the same PR count - it's ordered by name
https://trello.com/c/5ZxE3YXt/89-add-ordering-to-dashboard-views
=> Order items on dashboard

app.rb, lib/gateways/team.rb, lib/presenters/pull_requests_by_team.rb, lib/use_cases/send_slack_messages.rb, spec/gateways/team_spec.rb, spec/presenters/pull_requests_by_team_spec.rb, spec/use_cases/send_slack_messages_spec.rb, views/team.erb
https://trello.com/c/TZmItTHQ/95-change-default-slack-channel-to-govukdevelopers
Additionally we have added a link to the individual team page on the team name when viewing all teams
=> Change the default team to be 'govuk-developers'

README.md
https://trello.com/c/I6j4nRxQ/98-update-readme-to-be-consistent-with-the-template-provided-on-the-govuk-developer-docs
=> Update README to template provided in developer documentation

app.rb
Additionally fixes linting errors that werent caught on jenkins
=> Don't cache unless we're on production

lib/domain/pull_request.rb, lib/gateways/pull_request.rb, lib/use_cases/fetch_pull_requests.rb, spec/app_spec.rb, spec/dependaseal_spec.rb, spec/gateways/pull_request_spec.rb, spec/use_cases/fetch_pull_requests_spec.rb, spec/use_cases/send_slack_messages_spec.rb, views/gem.erb, views/index.erb
Show the review status on the dashboard - if the PR has been reviewed/changes have been requested, the status will display following the title
https://trello.com/c/v8veUH5B/96-display-if-a-pr-has-been-approved-or-not
=> Show review status

lib/presenters/slack/full_message.rb, spec/dependaseal_spec.rb, spec/presenters/slack/full_message_spec.rb
Create hyperlinks and display how many open pull requests an application has.
https://trello.com/c/5Ga6jRtA/102-improve-slack-message-content
=> Slack message improvements

Rakefile, dependapanda.rb, lib/gateways/slack_message.rb, spec/dependapanda_spec.rb, spec/gateways/slack_message_spec.rb
Use a Panda as the mascot since the seal mascot is taken.
https://trello.com/c/BtblVVub/103-rename-dependaseal-to-dependapanda
=> Rename to Dependapanda

README.md, Rakefile, app.rb, dependapanda.rb, lib/gateways/slack_message.rb, spec/app_spec.rb, spec/dependapanda_spec.rb, spec/gateways/slack_message_spec.rb
Don't allow anyone to manually request Slack messages, authorise this request.
https://trello.com/c/QJvuueKy/100-manually-request-a-slack-message
=> Authorise slack message requests

Rakefile, lib/gateways/gemfile.rb, lib/use_cases/fetch_gemfiles.rb, lib/use_cases/save_gemfiles.rb, spec/gateways/gemfile_gateway_spec.rb, spec/use_cases/fetch_gemfiles_spec.rb
Fetch all the Gemfiles for applications.  Save them in tmp, where the scanner can do the auditing.
https://trello.com/c/1ZuyqP0q/93-investigate-integrating-github-security-vulnerability-alerts
=> Fetch and Save Gemfiles For Security Auditing

README.md
Rendered version:
https://github.com/alphagov/govuk-dependencies/blob/3d4c72b85cf3d51afd2031f6b79e13a930615106/README.md
=> Add security alerts to the README

public/assets/application.css, views/security_alerts.erb
=> Style no open security alerts message

public/assets/application.css, views/layout.erb, views/stats.erb
=> Improve stats page and add link to it

app.rb, lib/use_cases/group/pull_requests_by_application.rb, lib/use_cases/group/pull_requests_by_gem.rb, views/gem.erb, views/index.erb
=> Inline some variables, default use cases

lib/presenters/slack/full_message.rb, lib/use_cases/group/applications_by_team.rb, spec/acceptance/dependapanda_spec.rb, spec/presenters/slack/full_message_spec.rb, spec/presenters/slack/simple_message_spec.rb, spec/use_cases/group/applications_by_team_spec.rb
- All the tests passed because I set the test URLs to the same, bugged
URL as the actual code. Ugh.
=> Append ?q= as the start of the `is:pr+is:open+label:dependencies` query

apps-script/Code.gs
Update appcript to show if repo is a gem or not.
https://trello.com/c/fK8LNfzA/3020-get-gems-marked-as-such-in-dependency-spreadsheet-3
=> Add gem row to appscript

apps-script/README.md
https://trello.com/c/fK8LNfzA/3020-get-gems-marked-as-such-in-dependency-spreadsheet-3
=> Add README for Apps Script
