lib/domain/pull_request.rb, lib/loader.rb, lib/use_cases/fetch_pull_requests.rb, spec/app_spec.rb, spec/fixtures/pull_requests.json, spec/spec_helper.rb, spec/use_cases/fetch_pull_requests_spec.rb
https://trello.com/c/HtR7PDed/58-get-prs-by-dependabot
Creates a use case for fetching pull requests. This will call a gateway which returns the PullRequest domain objects for every PR that is open for Dependabot, which will be written in a subsequent PR. 
Additionally this adds a failing feature spec for displaying a list of applications and their count of Dependabot PRs
=> Create FetchPullRequests Use Case

lib/loader.rb, lib/use_cases/send_slack_messages.rb, spec/use_cases/send_slack_messages_spec.rb
https://trello.com/c/cHx23NBz/74-generate-dependaseal-messages
There is currently duplication between this use_case and the team-view presenter that we'd like to refactor out, however to keep this PR easier to review we've kept this duplication in to refactor later
=> Add usecase for sending slack messages

lib/presenters/pull_requests_by_application.rb, lib/presenters/pull_requests_by_gem.rb, lib/presenters/pull_requests_by_team.rb, lib/use_cases/fetch_pull_requests.rb, spec/presenters/pull_requests_by_application_spec.rb, spec/presenters/pull_requests_by_gem_spec.rb, spec/presenters/pull_requests_by_team_spec.rb, spec/use_cases/fetch_pull_requests_spec.rb, views/gem.erb, views/index.erb
Dependabot sometimes bumps two gems at the same time and summarises the message that we depend on for generating results.
"Bump Rails from x to y"
"Bump Rspec from x to y"
becomes:
"Bump Rails and Rspec"
This is a refactoring to make it easier to address this bug in a usecase by decoupling the domain objects from the presenters.
https://trello.com/c/A43JQFQy/88-gem-view-bug-when-dependabot-bumps-2-gems-at-once-and-summarises-the-message
=> Refactor presenters to not know about domain objects

lib/domain/pull_request.rb, lib/presenters/pull_requests_by_gem.rb, lib/use_cases/fetch_pull_requests.rb, spec/presenters/pull_requests_by_gem_spec.rb, spec/use_cases/fetch_pull_requests_spec.rb
This caters for a summarised pull request title by Dependabot.
It splits a summarised pull request message into 2 separate pull requests to be displayed on the Gem view page.
https://trello.com/c/A43JQFQy/88-gem-view-bug-when-dependabot-bumps-2-gems-at-once-and-summarises-the-message
=> Gem view grouped pull requests bug

Gemfile, Gemfile.lock
Heroku scheduler was failing with the following message: 
`bundler: failed to load command: rake (/app/bin/rake)` as it was not in the gemfile
=> Add rake for heroku scheduler

app.rb, lib/domain/pull_request.rb, lib/use_cases/fetch_pull_requests.rb, public/assets/application.css, spec/gateways/pull_request_spec.rb, spec/use_cases/fetch_pull_requests_spec.rb, views/gem.erb, views/index.erb
The code to determine whether or not a PR is considered old is taken from the seal here: https://github.com/alphagov/seal/blob/master/lib/message_builder.rb
https://trello.com/c/R4VlA24a/97-indicate-old-prs-in-some-way
=> Indicate older PRs on the view page

app.rb
Due to running on different Dynos - we need to update this on the dyno the webserver is running on
=> Update advisory DB on requests to the security alerts page

lib/presenters/slack/full_message.rb, lib/presenters/slack/simple_message.rb, lib/use_cases/slack/schedulers/weekday.rb, spec/acceptance/dependapanda_spec.rb, spec/presenters/slack/full_message_spec.rb, spec/presenters/slack/simple_message_spec.rb, spec/use_cases/slack/schedulers/weekday_spec.rb
This makes the Slack messages smaller by putting all the repos on one line rather than on separate lines. I've also removed the feedback link as it doesn't seem to be used and we can take feedback in this repo.
Also fixed a bug meaning that messages were still being send on the weekend.
[Trello Card](https://trello.com/c/LpIHFgQv/34-2-stop-getting-spammed-in-slack-about-dependencies)
=> Make Slack messages smaller

lib/gateways/pull_request.rb, lib/gateways/pull_request_count.rb, lib/presenters/slack/full_message.rb, lib/use_cases/group/applications_by_team.rb, spec/acceptance/app_spec.rb, spec/acceptance/dependapanda_spec.rb, spec/gateways/pull_request_count_spec.rb, spec/gateways/pull_request_spec.rb, spec/presenters/slack/full_message_spec.rb, spec/presenters/slack/simple_message_spec.rb, spec/use_cases/group/applications_by_team_spec.rb
Github recently acquired Dependabot and the app was renamed so this app
stopped working. This PR should fix that.
https://dependabot.com/blog/hello-github/#what-is-happening-to-the-existing-dependabot-product
=> Update Dependabot app name

lib/use_cases/distribute/overflow_to_developers_channel.rb, lib/use_cases/slack/send_messages.rb, spec/use_cases/distribute/overflow_to_developers_channel_spec.rb
To help distribute Dependabot PRs a little more fairly around the
GOV.UK developer community, we want to be able to move some overflow
from teams into the general #govuk-developers channel.
Add a use case to distribute applications when a team has more than a defined overflow (set at a default of 15). This means when #platform-health has pull requests for more than 15 applications, the overflow (or application.count -15) will be distributed to the #govuk-developers channel instead of #platform-health.
Tap into the use case when sending slack messages.
This is not a very clever algorithm, but it's an experiment.
=> Add application overflow distribution

lib/presenters/slack/full_message.rb, lib/use_cases/group/applications_by_team.rb, spec/acceptance/dependapanda_spec.rb, spec/presenters/slack/full_message_spec.rb, spec/presenters/slack/simple_message_spec.rb, spec/use_cases/group/applications_by_team_spec.rb
- Since GitHub acquired Dependabot, its username has been alternating
between `app/dependabot` and `app/dependabot-preview`. This has the
annoying side effect that both usernames can raise PRs with the label
"dependencies", and the count of PRs (which searches for both
usernames) and the `application_url` link that lists the PRs sometimes
don't match up. For example, govuk_app_config has a correct count of 3
"dependencies" label PRs, raised by app/dependabot, but the
`application_url` was hardcoding `app/dependabot-preview` in the
filters.
- Get around this by using the more verbose but _correct_ `is:pr is:open
label:dependencies` search in the URL for the pull request page.
=> Get all PRs with label "dependencies" on a repo

Jenkinsfile
This is to stop every master build failing since this app isn't deployed
to integration (arguably this should be an opt-in rather than opt-out
given how frequently it causes problems)
=> Skip deploy to Integration on build

.rspec, lib/domain/team.rb, lib/gateways/team.rb, lib/presenters/slack/full_message.rb, lib/presenters/slack/simple_message.rb, lib/use_cases/slack/send_messages.rb, lib/use_cases/teams/fetch.rb, spec/fixtures/application_with_no_team.json, spec/fixtures/multiple_teams_with_multiple_applications.json, spec/fixtures/team_with_one_application.json, spec/fixtures/team_with_two_applications.json, spec/gateways/team_spec.rb, spec/presenters/slack/full_message_spec.rb, spec/presenters/slack/simple_message_spec.rb
Depends on https://github.com/alphagov/govuk-developer-docs/pull/2949 and https://github.com/alphagov/govuk-developer-docs/pull/2950.
This change draws attention to PRs which can be merged & deployed with one click, thanks to the Continuous Deployment process. This should mean developers are more open to merging Dependabot PRs.
> [taxonomy](https://govuk-dependencies.herokuapp.com/team/taxonomy) have 3 Dependabot PRs open on the following apps:
>
> [collections-publisher](https://github.com/alphagov/collections-publisher/pulls?q=is:pr+is:open+label:dependencies) (1) [content-tagger](https://github.com/alphagov/content-tagger/pulls?q=is:pr+is:open+label:dependencies) (2)
> [taxonomy](https://govuk-dependencies.herokuapp.com/team/taxonomy) have 1 Dependabot PRs open on the following …
=> Highlight CD-enabled apps in Dependabot messages

lib/presenters/slack/full_message.rb, lib/use_cases/distribute/overflow_to_developers_channel.rb, spec/use_cases/distribute/overflow_to_developers_channel_spec.rb
The first commit improves the conditional logic so that we don't see a "0 Dependabot PRs" message when there are CD repos for the current team, but no CD PRs:
The second commit fixes an oversight in #104 whereby `#govuk-developers` Dependabot messages are subject to an 'overflow' mechanism which meant the `continuously_deployed_apps` information was being filtered out.
=> Improve Continuously-Deployed apps logic

Gemfile, Gemfile.lock, Rakefile, app.json, app.rb, config/initializers/cache_store.rb, config/initializers/github_client.rb, lib/gateways/pull_request.rb, lib/gateways/pull_request_count.rb, lib/gateways/repositories.rb, lib/loader.rb, spec/acceptance/app_spec.rb, spec/config/initializers/cache_store_spec.rb, spec/gateways/pull_request_spec.rb, spec/gateways/repositories_spec.rb, spec/spec_helper.rb, spec/support/stub_helpers.rb
GithubAPI is rate limiting our authenticated requests. See [commit](https://github.com/alphagov/govuk-dependencies/commit/5a7c41a274b3c8b006191fab28487908ee7eda56) for details.
I have added a memcached store, which is well supported by Heroku. The cache is filled via a rake task run by the Heroku scheduler twice a day. 
- [trello](https://trello.com/c/eEIjWmvy/2768-stop-govuk-dependencies-app-being-rate-limited-by-github)
=> Add a cache and warm it up

lib/use_cases/slack/send_messages.rb
Everywhere in the codebase that takes a
`continuously_deployed_apps` parameter expects an array, not a
`nil`.
If I run the `dependapanda_loud` rake task in Heroku, it has been
failing with this message:
```
NoMethodError: undefined method `include?' for nil:NilClass
/app/lib/presenters/slack/full_message.rb:6:in `block in execute'
/app/lib/presenters/slack/full_message.rb:6:in `filter'
/app/lib/presenters/slack/full_message.rb:6:in `execute'
/app/lib/use_cases/slack/send_messages.rb:43:in `block in send_messages'
/app/lib/use_cases/slack/send_messages.rb:39:in `each'
/app/lib/use_cases/slack/send_messages.rb:39:in `send_messages'
/app/lib/use_cases/slack/send_messages.rb:25:in `execute'
/app/dependapanda.rb:15:in `send_full_message'
```
This PR should fix that.
Trello: …
=> Pass empty array instead of nil for `continuously_deployed_apps`

README.md, Rakefile, lib/gateways/pull_request.rb, lib/gateways/pull_request_count.rb, spec/acceptance/app_spec.rb, spec/acceptance/dependapanda_spec.rb, spec/gateways/pull_request_count_spec.rb, spec/support/stub_helpers.rb
Dependapanda has stopped notifying Slack since the end of March.
It seems like Github is being more aggressive in rate-limiting requests to their API.
This PR attempts to fix this by making API requests more spaced.
[Trello](https://trello.com/c/NpeMpcep/2886-fix-dependapanda-again-5)
=> Fix rate-limiting

lib/gateways/team.rb, spec/acceptance/app_spec.rb, spec/acceptance/dependapanda_spec.rb, spec/gateways/team_spec.rb
This uses a new endpoint, repos.json [1], to access the GOV.UK
repositories. The apps.json endpoint only returns running applications,
which means that Gems and similar non-running apps aren't including.
Switching to repos.json will include those projects
~~This is open as a draft whilst https://github.com/alphagov/govuk-developer-docs/pull/3481 is open.~~ I also found that I had problems running this due to secondary rate-limiting so it's been hard to test, not sure if there are any tips?
[1]: https://github.com/alphagov/govuk-developer-docs/pull/3481
=> Use repos.json to access GOV.UK repositories

lib/domain/team.rb, lib/gateways/team.rb, lib/presenters/slack/full_message.rb, lib/presenters/slack/simple_message.rb, lib/use_cases/distribute/overflow_to_developers_channel.rb, lib/use_cases/slack/send_messages.rb, lib/use_cases/teams/fetch.rb, spec/gateways/team_spec.rb, spec/presenters/slack/full_message_spec.rb, spec/presenters/slack/simple_message_spec.rb, spec/use_cases/distribute/overflow_to_developers_channel_spec.rb
The 'continuously deployed apps' logic ([1]) has been broken for a long time.
[1]: https://github.com/alphagov/govuk-dependencies/blob/e245152349ed4428ead26de42ca3e344efd454b5/lib/presenters/slack/full_message.rb#L7-L14
This is because govuk-dependencies tries to read that info from the Developer Docs ([2]).
[2]: https://github.com/alphagov/govuk-dependencies/blob/6d9dfbae47e5e866d676cb2285e0fef93406153d/lib/gateways/team.rb#L7-L16
However, we removed that from the Developer Docs in October 2021 ([3]).
[3]: https://github.com/alphagov/govuk-developer-docs/commit/5f667af9ae00abf969a80408358409eeca97e7b1
Whilst we could in theory retrieve that info from the Release app now ([4]), not
all repos retrieved by govuk-dependencies has a corresponding app in the Release
app, and the JSON endpoints …
=> Remove all Continuous Deployment related logic

lib/presenters/slack/full_message.rb, lib/use_cases/group/applications_by_team.rb, spec/acceptance/dependapanda_spec.rb, spec/fixtures/pull_requests.json, spec/gateways/pull_request_spec.rb, spec/presenters/slack/full_message_spec.rb, spec/use_cases/group/applications_by_team_spec.rb
Made adjustments to Dependapanda, so that when it looks at PRs, it will show
the age of the oldest PR if there are multiple, or when it's only a single PR, it displays its age as well.
Trello card: https://trello.com/c/sWcTRRN1/2951-configure-dependapanda-to-report-on-how-long-prs-have-been-open
=> Configure Dependapanda to report PR age

lib/use_cases/group/applications_by_team.rb, spec/use_cases/group/applications_by_team_spec.rb
For each application, Dependapanda is specifying when the oldest pr was opened. This information is not correct when an applications has prs opened "today" or "yesterday".
=> Check the oldest pr by the date it was opened

lib/use_cases/group/applications_by_team.rb, spec/use_cases/group/applications_by_team_spec.rb, spec/use_cases/slack/send_messages_spec.rb
Changed main sorting criterion from open_since to opened_at to make
sure we sort by actual dates, and no mishaps happen from string open_since values.
Applied sorting priority order as oldest pr, followed by number of open prs, followed by alphabetical.
Trello card: https://trello.com/c/lPnjZ77E/2959-improve-ordering-of-dependapanda-slack-message
=> Improving Dependapanda message sorting

lib/gateways/slack_message.rb, lib/use_cases/slack/send_messages.rb, spec/acceptance/dependapanda_spec.rb
Made changes so that when Dependapanda executes but gets an error from Slack API because the channel it is trying to post is missing/does not exist, then it notifies the Platform Reliability team, so we get a warning that those reminders will not reach their intended recipients.
Trello card: https://trello.com/c/6u6FCg0L/2977-get-dependapanda-to-alert-if-the-channel-doesnt-exist-3
=> Alert the Platform Reliability team if a channel does not exist

apps-script/Code.gs
We have this Apps Script 'installed' on the following Google sheet: https://docs.google.com/spreadsheets/d/1Lt-uarJm1xaCEC58KdSixsa5LsBSmNXym37SbuXbrcI/edit
It allows you to retrieve the latest repo list from the Developer Docs, and then retrieve the versions of some key dependencies for each repo (Ruby, Rails, Sidekiq, etc).
Note that the Apps Script is a JavaScript based platform: https://developers.google.com/apps-script
This code isn't directly related to govuk-dependencies, but is very closely linked to what govuk-dependencies aims to do. So rather than create a new repo just for one file, we're adding it here.
=> Commit Apps Script to GitHub

apps-script/Code.gs
There is now a single "Refresh Repos tab" menu item which, when triggered, clears the 'Repos' tab and then:
- Downloads the list of repos from the Developer Docs, populating columns A and B
- Fetches dependency information for each of the dependencies we care about
=> Clear and repopulate Repos sheet from one action
